Task 2.10   edicio del perfil del usuario/122
ciaolavoro/ciao-lavoro pull request #197
Opened 2024-03-16 17:03 UTC by adrgarcha

Se ha agregado la posibilidad de editar tu propio perfil. No se contempla la posibilidad de poder cambiar la contraseña, ya que no se ha añadido dicha posibilidad ni la validación pertinente en la parte del Backend.

2024-03-17 11:48 UTC, javgrogom requested changes
La rama tiene conflictos

2024-03-17 15:54 UTC, adrgarcha commented
Probablemente no aparezca la foto de vuestro usuario, debido a que todavía no posee una foto en la base de datos. Bastaría con actualizar vuestro propio perfil con una foto y ya podréis verla. Remarcar que las fotos están ignoradas en el gitignore para no subir grandes cantidades de imágenes al repositorio.

2024-03-17 17:31 UTC, alisanhos requested changes
Cuando voy a editar el perfil, me obliga a cambiar la foto si o si, no debería ser obligatorio.

![imagen](https://github.com/ciaolavoro/ciao-lavoro/assets/59439742/aacf3d40-3946-4184-922c-2de84d037cdf)

Otro error que he encontrado es que a pesar de modificar el Username, en la base de datos no se cambia. Sigue siendo waos cuando se supone que debería ser Waos1605

![imagen](https://github.com/ciaolavoro/ciao-lavoro/assets/59439742/b247f0ae-98a2-4266-b4de-ee0264e52f55)

2024-03-19 08:14 UTC, FranCamposC submitted a review, later dismissed
Da error 500  al cambiar el nombre de usuario por uno ya existente en la base de datos.

2024-03-20 13:20 UTC, alisanhos approved these changes
Todos los cambios que se solicitaron están arreglados

2024-03-20 14:06 UTC, merged