Fix 6 - Adición del campo Username a la edición de perfil de Usuario …
ciaolavoro/ciao-lavoro pull request #208
Opened 2024-03-17 20:45 UTC by diegonqui

…#203

2024-03-17 22:21 UTC, Joaquin-Arregui requested changes
El usuario debería obtenerse a partir del token. La función actualmente no funcionaría en una conexión frontend-backend
![image](https://github.com/ciaolavoro/ciao-lavoro/assets/72920772/ff1e703a-a686-4b50-bf03-3dc3ca62a4ca)

2024-03-18 07:35 UTC, adrgarcha commented
@Joaquin-Arregui El usuario al editar su perfil es obligado a cerrar sesión para mantener el token y su información actualizados a como ha definido el usuario. Se podría cambiar el nombre de usuario sin problema.

2024-03-18 15:42 UTC, Samalbalat commented
Se ha cambiado la obtención del usuario para respetar las vías de seguridad a una obtención mediante su token

![Captura de pantalla 2024-03-18 164103](https://github.com/ciaolavoro/ciao-lavoro/assets/80246257/f51bf50b-538c-431e-b5a7-10fe86efd6a7)

2024-03-18 16:49 UTC, Joaquin-Arregui requested changes
Al hacer el commit se ha olvidado quitar un print

2024-03-18 16:51 UTC, Samalbalat approved these changes

2024-03-18 16:53 UTC, Joaquin-Arregui approved these changes
Funciona todo bien

2024-03-18 16:53 UTC, merged