Hotfix 3 arreglo errores relacionados con servicio/231 DONE
ciaolavoro/ciao-lavoro pull request #247
Opened 2024-03-21 18:04 UTC by Antonio23337

#231 

Añadida validaciones y limpieza de código para el modelo de Servicio

2024-03-22 12:27 UTC, Samalbalat requested changes
Mira bien como haces la restricciones del views.py

2024-03-22 12:27 UTC, Samalbalat commented on backend/service/views.py
Utiliza el método .strip() para asegurarte de que es cualquier número de espacios en blanco, y asegurate de que vienen expresados los campos con:
if (datos['nombre_del_campo] and datos['nombre_del_campo].strip != '')

Lo anterior mira si ese valor existe en los datos y si no es todo espacios, luego asignas la variable y sino saltas con un validación

Estimated_price en job no parece estar bien hecho

Creo que la restricción de servicios está bien hecha en teoría

2024-03-23 14:15 UTC, diegonqui commented on backend/service/views.py
Petición de cambios realizada. Gracias por la ayuda

2024-03-23 14:27 UTC, diegonqui approved these changes
Mi revisión ha sido finalizada y todo se ve correcto

2024-03-23 14:28 UTC, Samalbalat approved these changes

2024-03-23 14:30 UTC, merged