Fix 18   validaciones editar servicio#227
ciaolavoro/ciao-lavoro pull request #255
Opened 2024-03-22 13:41 UTC by pabmatang

Fix 18,Fix17, arreglar editar Servicio, arreglar editar Job

2024-03-22 20:40 UTC, adrgarcha requested changes
He cambiado algunas partes del código. Sin embargo, es necesario realizar ciertos cambios:

- Al crear/editar un trabajo, no hay ningún tipo de validación.
- El componente Service es demasiado grande y tiene lógica que no le pertenece a los servicios sino a los trabajos, separar en un componente aparte la lista de trabajos.
- Soy el usuario del servicio y no aparece el botón para editarlo.
- Editar los estilos de los botones de actualizar trabajo, no están centrados y necesita un poco de espacio abajo de ellos.
- Actualizar las validaciones de editar servicio, que he agregado una nueva.

2024-03-23 11:51 UTC, FranCamposC commented
Se han solucionado la mayoria de errores:

-Falta dividir el componente Service.jsx
-Validacion de que la experiencia no pueda ser mayor que  tu edad-16 años

2024-03-23 13:35 UTC, alisanhos commented
Solo faltaría dividir el componente Service.jsx y sacar el listJobs en un .jsx aparte.

2024-03-23 17:04 UTC, adrgarcha approved these changes

2024-03-23 17:04 UTC, merged