Fix P.5 - servicios/509 DONE
ciaolavoro/ciao-lavoro pull request #527
Opened 2024-05-02 15:55 UTC by pabcueper

2024-05-02 19:08 UTC, javgrogom commented
No me deja actualizar los años de experiencia de un servicio:

![image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/2df9e238-4369-4070-bdb3-d09be6e6b6ca)


El resto funciona bien

2024-05-02 19:09 UTC, javgrogom requested changes
Mira el comentario de arriba.

Funciona mal el editar experiencia de usuario:
![image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/adf50189-0556-4e3d-84c7-812230c67928)

2024-05-04 14:01 UTC, alisanhos approved these changes
He revisado el cambio que solicitó Javier y funciona sin problemas

2024-05-04 14:01 UTC, Joaquin-Arregui approved these changes
Funciona todo correctamente

2024-05-04 14:40 UTC, javgrogom approved these changes

2024-05-04 14:40 UTC, merged